---
title: "Migration Type Classification"
subtitle: "Master in Bioinformatics, University of Murcia"
author: "Joaquín Cantón Sandoval (joaquin.canton@um.es)"
date: "`r Sys.Date()`"
output:
  html_document:
    df_print: paged
    highlight: kate
    number_sections: true
    theme: spacelab
    toc: yes
    toc_float: yes
---

```{r setup, include=FALSE} 
knitr::opts_chunk$set(warning = FALSE, message = FALSE) 
```

# Classifying Migration Types of Neutrophils

This document provides a method for classifying the migration types of neutrophils based on their interaction with aggregates.

```{r}
# Load necessary libraries
library(dplyr)
library(readr)

# Define the function to classify migration types
classify_migration_type <- function(neutrofilos) {
  # Inicializar la nueva columna con NA para luego determinar los valores correctos
  neutrofilos$Type.Of.Migration <- NA
  
  # Iterar sobre cada trackID único en los datos de neutrófilos
  unique_tracks <- unique(neutrofilos$TrackID)
  for(trackID in unique_tracks) {
    track_indices <- which(neutrofilos$TrackID == trackID)
    datos_neutrofilo <- neutrofilos[track_indices, ]
    
    # Determinar el tipo de migración para cada timepoint
    for(i in seq_along(datos_neutrofilo$TrackID)) {
      if(datos_neutrofilo$Neutrophil.Is.Interacting[i] == 1) {
        neutrofilos$Type.Of.Migration[track_indices[i]] <- 0
      } else {
        if(all(datos_neutrofilo$Neutrophil.Aggregate.Contact.Number == 0)) {
          neutrofilos$Type.Of.Migration[track_indices[i]] <- 4
        } else {
          current_contact_number <- datos_neutrofilo$Neutrophil.Aggregate.Contact.Number[i]
          future_contact_numbers <- datos_neutrofilo$Neutrophil.Aggregate.Contact.Number[i:length(datos_neutrofilo$Neutrophil.Aggregate.Contact.Number)]
          
          if(current_contact_number == 0 && any(future_contact_numbers > 0)) {
            neutrofilos$Type.Of.Migration[track_indices[i]] <- 1
          } else if(current_contact_number > 0 && all(future_contact_numbers == current_contact_number)) {
            neutrofilos$Type.Of.Migration[track_indices[i]] <- 3
          } else if(current_contact_number > 0 && any(future_contact_numbers > current_contact_number)) {
            neutrofilos$Type.Of.Migration[track_indices[i]] <- 2
          }
        }
      }
    }
  }
  
  # Convertir la columna a factor con los niveles especificados
  neutrofilos$Type.Of.Migration <- factor(neutrofilos$Type.Of.Migration, levels = c(0, 1, 2, 3, 4))
  
  return(neutrofilos)
}

neutrophils_with_distance <- read.csv("neutrophils_with_distance.csv")
neutrophils_with_migration <- classify_migration_type(neutrophils_with_distance)
head(neutrophils_with_migration[, c("ID", "TrackID", "TimePoint", "Type.Of.Migration")])
write.csv(neutrophils_with_migration, "neutrophils_with_migration.csv")
```


