---
title: "Neutrophil Interaction With Other Neutrophils"
subtitle: "Master in Bioinformatics, University of Murcia"
author: "Joaquín Cantón Sandoval (joaquin.canton@um.es)"
date: "`r Sys.Date()`"
output:
  html_document:
    df_print: paged
    highlight: kate
    number_sections: true
    theme: spacelab
    toc: yes
    toc_float: yes
---

```{r setup, include=FALSE} 
knitr::opts_chunk$set(warning = FALSE, message = FALSE) 
```

# Analyzing Neutrophil Interaction With Other Neutrophils

This document focuses on the calculation of neutrophil interactions with other neutrophils to identify potential aggregation behavior.

```{r}
# Load necessary libraries
library(dplyr)
library(readr)
library(sets)

# Define helper functions for distance and radius calculations
distancia_euclidiana <- function(x1, y1, z1, x2, y2, z2) {
  sqrt((x2 - x1)^2 + (y2 - y1)^2 + (z2 - z1)^2)
}

calcular_radio_esfera <- function(volume) {
  (3 * volume / (4 * pi))^(1/3)
}

calculate_neutrophil_interactions <- function(neutrofilos) {
  
  neutrofilos$Number.Of.Neutrophil.Contacts <- integer(nrow(neutrofilos))
  neutrofilos$Track.Number.Of.Neutrophil.Contacts <- integer(nrow(neutrofilos))
  neutrofilos$Interaction.With.Neutrophils <- integer(nrow(neutrofilos))
  
  
  neutrofilos_por_timepoint <- split(neutrofilos, neutrofilos$TimePoint)
  
  for(timepoint in names(neutrofilos_por_timepoint)) {
    datos <- neutrofilos_por_timepoint[[timepoint]]
    n <- nrow(datos)
    
    for(i in 1:n) {
      contacto <- FALSE
      for(j in 1:n) {
        if(i != j) {
          distancia <- distancia_euclidiana(datos$Position.X[i], datos$Position.Y[i], datos$Position.Z[i],
                                            datos$Position.X[j], datos$Position.Y[j], datos$Position.Z[j])
          if(distancia <= calcular_radio_esfera(datos$Volume[i]) + calcular_radio_esfera(datos$Volume[j])) {
            contacto <- TRUE
            break
          }
        }
      }
      
      neutrofilos$Interaction.With.Neutrophils[neutrofilos$ID == datos$ID[i]] <- as.integer(contacto)
    }
  }
  
  
  neutrofilos <- neutrofilos %>%
    arrange(TrackID, TimePoint) %>%
    group_by(TrackID) %>%
    mutate(Number.Of.Neutrophil.Contacts = cumsum(Interaction.With.Neutrophils),
           Track.Number.Of.Neutrophil.Contacts = max(Number.Of.Neutrophil.Contacts))
  
  return(neutrofilos)
}

neutrophils_with_migration <- read.csv("neutrophils_with_migration.csv")
neutrophils_with_contacts <- calculate_neutrophil_interactions(neutrophils_with_migration)

neutrophils_with_contacts <- neutrophils_with_contacts %>%
  mutate(Neutrophil.Which.Interacts.With.Neutrophils = ifelse(Track.Number.Of.Neutrophil.Contacts > 0, 1, 0))

neutrophils_with_contacts$Neutrophil.Which.Interacts.With.Neutrophils <- factor(neutrophils_with_contacts$Neutrophil.Which.Interacts.With.Neutrophils, levels = c(0, 1))

neutrophils_with_contacts$Interaction.With.Neutrophils <- factor(neutrophils_with_contacts$Interaction.With.Neutrophils, levels = c(0, 1))


head(neutrophils_with_contacts[, c("ID", "TrackID", "TimePoint", "Number.Of.Neutrophil.Contacts", "Track.Number.Of.Neutrophil.Contacts", "Interaction.With.Neutrophils", "Neutrophil.Which.Interacts.With.Neutrophils")])

write.csv(neutrophils_with_contacts, "neutrophils_with_contacts.csv")
```

