---
title: "Proximity Analysis of Neutrophils"
subtitle: "Master in Bioinformatics, University of Murcia"
author: "Joaquín Cantón Sandoval (joaquin.canton@um.es)"
date: "`r Sys.Date()`"
output:
  html_document:
    df_print: paged
    highlight: kate
    number_sections: true
    theme: spacelab
    toc: yes
    toc_float: yes
---

```{r setup, include=FALSE} 
knitr::opts_chunk$set(warning = FALSE, message = FALSE) 
```

# Measuring Neutrophils in Proximity

This document describes the method to quantify the number of neutrophils in proximity to each other, which can be indicative of clustering behavior.

```{r}
# Load necessary libraries
library(dplyr)
library(readr)
library(sets)

# Define helper functions for distance and radius calculations
distancia_euclidiana <- function(x1, y1, z1, x2, y2, z2) {
  sqrt((x2 - x1)^2 + (y2 - y1)^2 + (z2 - z1)^2)
}

calcular_radio_esfera <- function(volume) {
  (3 * volume / (4 * pi))^(1/3)
}

calculate_neutrophil_proximity <- function(neutrophils) {
  
  neutrophils$Position.X <- as.numeric(neutrophils$Position.X)
  neutrophils$Position.Y <- as.numeric(neutrophils$Position.Y)
  neutrophils$Position.Z <- as.numeric(neutrophils$Position.Z)
  neutrophils$Volume <- as.numeric(neutrophils$Volume)
  
  # Calcular el radio basado en el doble del volumen
  radio_ampliado <- function(volumen) {
    (3 * (2 * volumen) / (4 * pi))^(1/3)
  }
  
  # Inicializar columna para contar los neutrófilos cercanos
  neutrophils$Neutrophils.Nearby <- rep(0, nrow(neutrophils))
  
  # Iterar por cada TimePoint
  for (timepoint in unique(neutrophils$TimePoint)) {
    indices_timepoint <- which(neutrophils$TimePoint == timepoint)
    for (i in indices_timepoint) {
      x_i <- neutrophils$Position.X[i]
      y_i <- neutrophils$Position.Y[i]
      z_i <- neutrophils$Position.Z[i]
      radio_i_ampliado <- radio_ampliado(neutrophils$Volume[i])
      
      contador_cercanos <- 0
      for (j in indices_timepoint) {
        if (i != j) {
          distancia <- distancia_euclidiana(x_i, y_i, z_i, neutrophils$Position.X[j], neutrophils$Position.Y[j], neutrophils$Position.Z[j])
          radio_j <- (3 * neutrophils$Volume[j] / (4 * pi))^(1/3)
          
          if (distancia <= (radio_i_ampliado + radio_j)) {
            contador_cercanos <- contador_cercanos + 1
          }
        }
      }
      
      # Actualizar el conteo de neutrófilos cercanos directamente en el dataframe original
      neutrophils$Neutrophils.Nearby[i] <- contador_cercanos
    }
  }
  
  return(neutrophils)
}

neutrophils_with_migration <- read.csv("neutrophils_with_migration.csv")

neutrophils_proximity <- calculate_neutrophil_proximity(neutrophils_with_migration)
head(neutrophils_proximity[, c("ID", "TrackID", "TimePoint", "Neutrophils.Nearby")])
```

