---
title: "Total Interaction Duration"
subtitle: "Master in Bioinformatics, University of Murcia"
author: "Joaquín Cantón Sandoval (joaquin.canton@um.es)"
date: "`r Sys.Date()`"
output:
  html_document:
    df_print: paged
    highlight: kate
    number_sections: true
    theme: spacelab
    toc: yes
    toc_float: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Calculate Total Interaction Duration

This document describes the procedure to convert the interaction timepoints into total interaction duration in seconds.

```{r}
updated_neutrophils = read.csv("updated_neutrophils.csv")

# Define the conversion factor (one timepoint to seconds)
conversion_factor <- 131.734

# Function to convert timepoints to seconds
convert_timepoints_to_seconds <- function(neutrophils) {
  neutrophils$Total.Interaction.Duration <- neutrophils$TimePoints.Interacting * conversion_factor
  neutrophils$Track.Total.Interaction.Duration <- neutrophils$Track.TimePoints.Interacting * conversion_factor
  
  return(neutrophils)
}

# Apply conversion
neutrophils_with_duration <- convert_timepoints_to_seconds(updated_neutrophils)
head(neutrophils_with_duration[, c("ID", "TrackID", "TimePoint", "Total.Interaction.Duration", "Track.Total.Interaction.Duration")])
write.csv(neutrophils_with_duration, "neutrophils_with_duration.csv")
```



