---
title: "Contact Start"
subtitle: "Master in Bioinformatics, University of Murcia"
author: "Joaquín Cantón Sandoval (joaquin.canton@um.es)"
date: "`r Sys.Date()`"
output:
  html_document:
    df_print: paged
    highlight: kate
    number_sections: true
    theme: spacelab
    toc: yes
    toc_float: yes
---

```{r setup, include=FALSE} 
knitr::opts_chunk$set(warning = FALSE, message = FALSE) 
```

# Calculate Contact Start

This document explains the method to determine the start of contact between a neutrophil and a keratinocyte aggregate.

```{r}
# Load required libraries
library(dplyr)
library(readr)

# Load data
neutrophils <- read_csv("updated_neutrophils.csv")  # Ensure this points to your data
aggregates <- read_csv("../../agregados_dmso1.csv")  # Ensure this points to your data

# Define helper functions for distance and radius calculations
distance_euclidean <- function(x1, y1, z1, x2, y2, z2) {
  sqrt((x2 - x1)^2 + (y2 - y1)^2 + (z2 - z1)^2)
}

calculate_sphere_radius <- function(volume) {
  (3 * volume / (4 * pi))^(1/3)
}

# Define a function to calculate the start of contact
calculate_contact_start <- function(neutrophils, aggregates, threshold_distance = 10) {
  neutrophils$NewContact <- 0

  # Iterate through each unique trackID
  for(trackID in unique(neutrophils$TrackID)) {
    track_data <- neutrophils[neutrophils$TrackID == trackID, ]
    previous_contact <- FALSE

    # Iterate through each row in track data
    for(i in 1:nrow(track_data)) {
      neutrophil_position <- track_data[i, c("Position.X", "Position.Y", "Position.Z")]
      neutrophil_volume <- track_data[i, "Volume"]
      neutrophil_radius <- calculate_sphere_radius(neutrophil_volume)

      current_contact <- FALSE

      # Check against all aggregates
      for(j in 1:nrow(aggregates)) {
        aggregate_position <- aggregates[j, c("Position.X", "Position.Y", "Position.Z")]
        aggregate_volume <- aggregates[j, "Volume"]
        aggregate_radius <- calculate_sphere_radius(aggregate_volume)

        # Calculate the adjusted distance
        distance <- distance_euclidean(neutrophil_position[1], neutrophil_position[2], neutrophil_position[3],
                                        aggregate_position[1], aggregate_position[2], aggregate_position[3])
        
        # Determine contact
        if(distance <= (neutrophil_radius + aggregate_radius + threshold_distance)) {
          current_contact <- TRUE
          if(!previous_contact) {
            neutrophils$NewContact[neutrophils$ID == track_data[i, "ID"]] <- 1
          }
          break
        }
      }
      
      previous_contact <- current_contact
    }
  }

  return(neutrophils)
}

# Apply the function
neutrophils_with_contact_start <- calculate_contact_start(neutrophils, aggregates)
head(neutrophils_with_contact_start[, c("ID", "TrackID", "TimePoint", "NewContact")])

write.csv(neutrophils_with_contact_start, "neutrophils_with_contact_start.csv")
```

