---
title: "Distance to Aggregates"
subtitle: "Master in Bioinformatics, University of Murcia"
author: "Joaquín Cantón Sandoval (joaquin.canton@um.es)"
date: "`r Sys.Date()`"
output:
  html_document:
    df_print: paged
    highlight: kate
    number_sections: true
    theme: spacelab
    toc: yes
    toc_float: yes
---

```{r setup, include=FALSE} 
knitr::opts_chunk$set(warning = FALSE, message = FALSE) 
```

# Calculate distance to the closest keratinocyte aggregate

This document details how to calculate the closest distance of a neutrophil to a keratinocyte aggregate.

```{r}
# Load necessary libraries
library(dplyr)
library(readr)
library(sets)

# Define helper functions for distance and radius calculations
distancia_euclidiana <- function(x1, y1, z1, x2, y2, z2) {
  sqrt((x2 - x1)^2 + (y2 - y1)^2 + (z2 - z1)^2)
}

calcular_radio_esfera <- function(volume) {
  (3 * volume / (4 * pi))^(1/3)
}
calcular_distancias_a_agregados <- function(neutrofilos, agregados) {
  # Añadir columnas para almacenar las distancias mínimas y la distancia media por track
  neutrofilos$Distance.To.Aggregate <- NA
  neutrofilos$Track.Mean.Distance.To.Aggregate <- NA
  
  # Iterar sobre cada trackID único en los datos de neutrófilos
  for(trackID in unique(neutrofilos$TrackID)) {
    # Filtrar las filas correspondientes a este trackID
    datos_neutrofilo <- neutrofilos[neutrofilos$TrackID == trackID,]
    
    # Inicializar un vector para almacenar las distancias mínimas de cada neutrófilo a los agregados
    distancias_minimas <- numeric(nrow(datos_neutrofilo))
    
    # Iterar sobre cada fila (timepoint) del neutrófilo
    for(i in 1:nrow(datos_neutrofilo)) {
      neutrofilo <- datos_neutrofilo[i,]
      
      # Calcular la distancia de este neutrófilo a todos los agregados y obtener la mínima
      distancias <- sapply(1:nrow(agregados), function(j) {
        distancia_euclidiana(neutrofilo$Position.X, neutrofilo$Position.Y, neutrofilo$Position.Z, 
                             agregados[j,]$Position.X, agregados[j,]$Position.Y, agregados[j,]$Position.Z)
      })
      distancia_minima <- min(distancias)
      distancias_minimas[i] <- distancia_minima
      
      # Asignar la distancia mínima a la columna correspondiente
      neutrofilos$Distance.To.Aggregate[neutrofilos$ID == neutrofilo$ID] <- distancia_minima
    }
    
    # Calcular y asignar el valor medio de las distancias mínimas para este trackID
    distancia_media_track <- mean(distancias_minimas)
    neutrofilos$Track.Mean.Distance.To.Aggregate[neutrofilos$TrackID == trackID] <- distancia_media_track
  }
  
  return(neutrofilos)
}

neutrofilos_contiempodeinteraccion <- read.csv("neutrophils_with_interaction_time.csv")
agregados <- read_csv("../../agregados_dmso1.csv")
neutrofilos_con_distancia <- calcular_distancias_a_agregados(neutrofilos_contiempodeinteraccion, agregados)
head(neutrofilos_con_distancia[, c("ID", "TrackID", "TimePoint", "Distance.To.Aggregate", "Track.Mean.Distance.To.Aggregate")])
write.csv(neutrofilos_con_distancia, "neutrophils_with_distance.csv")
```



